all: 
	g++ -o main main.cpp crossover.cpp mutate.cpp population.cpp genetic.cpp properties.cpp -lsystemc -lm

	
matlab:
	g++ -o matlab matlab.cpp crossover.cpp mutate.cpp population.cpp genetic.cpp properties.cpp -lsystemc -lm

clean:
	rm main matlab